apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers
kubernetesVersion: stable
apiServer:
  certSANs:
  - "172.16.0.222"
controlPlaneEndpoint: "172.16.0.222:6443"
etcd:
  external:
    endpoints:
    - https://172.16.0.215:2379
    - https://172.16.0.216:2379
    - https://172.16.0.217:2379
    caFile: /etc/etcd/ssl/ca.pem
    certFile: /etc/etcd/ssl/etcd.pem
    keyFile: /etc/etcd/ssl/etcd-key.pem
networking:
  podSubnet: 10.0.0.0/8
